### ISSUE TITLE
Convert string into ASCII

### ISSUE THREAD

**Issue by badbeef** [Shopify/liquid#1055]
I have a need to convert a string into a sequence of ASCII (in hex). I have look through all the available operators. I managed to use "split" to slice a string into individual characters but I am stuck at this point. I don't want to write 100+ lines of {% when 'x' %}. Is there a better alternative?

**Comment by keralab** [comment]
@fw42 
I'm working on implementing this for a university course, but had a question about testing this in the liquid examples. 
I can run the server and get the products page, but when I try using my new filter (`string_to_ascii`) that change is not reflected in the products page. My guess is that its not using my updated version of the liquid gem. How can I change it so that I can see my new filter being used?
Here is my fork: https://github.com/keralab/liquid
Thanks for your help!

**Comment by nickpearson** [comment]
Here's a pretty simple way to test without having to run a server. Start a new irb session by running `bundle console` from your `liquid` directory, then parse and render a template to test your new filter.

```ruby
Liquid::Template.parse("{{ 'hello' | string_to_ascii | join: ', ' }}").render
# => "68, 65, 6c, 6c, 6f"
```

Lastly, you can avoid iterating twice by combining the two `map` calls:

```ruby
input.chars.map{ |c| c.ord.to_s(16) }
```

(I don't know if `chars` is faster than `split('')`, but it may be a bit more clear.)

Hope this helps. :)

**Comment by shopmike** [comment]
Just closing this off as it looks like everything has been solved here. I think the next step for this would be a PR if you wanted to try and bring this into Liquid.
