### ISSUE TITLE
Request for suggestions: Liquid comments

### ISSUE THREAD

**Issue by tobi** [Shopify/liquid#1393]
Right now comments in liquid are implemented through the `{% comment %}` tag. Basically a block that doesn't do anything. 

This has always been clunky and I think we should introduce syntax for this. 

This is especially true because of the new liquid block tag. Consider that this is the only way to do inline comments right now:

```
{% liquid
comment Is the feature_image set? 
endcomment

if product.featured_image
  echo product.featured_image | img_tag
else
  echo 'product-1' 
endif 
%}
```

Which... is bad. 

My current thinking is that we should double down on our ruby heritage and designate `#` as the comment character. Alternatives here would be c style `//` or lua style `--`

This would transform the above to 
```
{% liquid
# Is the feature_image set? 
if product.featured_image
  echo product.featured_image | img_tag
else
  echo 'product-1' 
endif 
%}
```

Additionally we could introduce a new inline token for comments:
Single line comment `{# comment #}` and multiline comments would be both supported 
```
{# 
  First line 
  Second line
#}
```

The downside of this syntax is that it may cause collisions in existing liquid code. We can (but haven't) check the Shopify databases for how common this might be.

**Comment by samdoiron** [comment]
Just prototyped this now, and Liquid's existing parsing logic requires that tags match the `\w+`. `--` does, which might make it a nicer option.

**Comment by tobi** [comment]
OK that makes perfect sense and means that we don't need a new tag at all. 

The one question is whitespace management. I'd like for comments to imply {%- -%} whitespace eating. Perhaps we can just introduce (or do we already do that?) a rule that a tag that doesn't output anything itself always eats surrounding whitespace. I imagine this would change resulting HTML, especially with common if and for tags. But... that's probably good? 

HTML doesn't care much about whitespace but plain text does. Many use cases of liquid exist around plain text, so if we change the default we definitely need a fallback.

**Comment by resistorsoftware** [comment]
In my long life of writing code, I have almost never run into trouble using the hash # symbol to introduce a comment, but I have had a lot of trouble with the double-slash // and its block companion /* */ so I am all over this introduction of a single tag symbol to open a comment. Also, the new liquid block is sexy. Super nice and also somewhat amazing that it took so long to evolve! You know it is right when it just feels right and not forced.

**Comment by ashukasma** [comment]
I would prefer to use **#** because the same work with shopify scripts, more towards ruby comments.

single line comment should work with **#**
multiple line comment can still with {%comment%}
{% endcomment%}

**Comment by CalinR** [comment]
Definitely prefer to use # as well. {# comment #} looks pretty clean too.

**Comment by 0kzh** [comment]
Since templating engines "inject code," it makes sense to use `#` like we do in Ruby, for consistency reasons.
I also like @samdoiron 's suggestion as in the following,
```
{# 
  First line 
  Second line
#}
```
`First line` and `Second line` might be wrongly interpreted as expressions.

**Comment by CalinR** [comment]
Definitely prefer to use #. I agree with @ashukasma that it keeps some consistency with Shopify scripts.

I think it make sense to use {# comment #} instead of doing {% # comment %} as you now have to deal with white space control which will cause you to have to do {%- # comment -%}. Instead you could just have {# comment #} remove whitespace by default.

**Comment by bworwa** [comment]
> OK that makes perfect sense and means that we don't need a new tag at all.
> 
> The one question is whitespace management. I'd like for comments to imply {%- -%} whitespace eating. Perhaps we can just introduce (or do we already do that?) a rule that a tag that doesn't output anything itself always eats surrounding whitespace. I imagine this would change resulting HTML, especially with common if and for tags. But... that's probably good?
> 
> HTML doesn't care much about whitespace but plain text does. Many use cases of liquid exist around plain text, so if we change the default we definitely need a fallback.

I never understood why whitespaces in control tags were a thing. Having 80+ white lines where a `for` used to be adds nothing but extra payload to the resulting document. They should all eat whitespaces by default.

I agree on the `{% #` , the reason why `{#` is not viable is because it will break inline CSS. E.g: `@media(...){#mydiv` will break the parser.

**Comment by tobi** [comment]
Yea, you are right that {# can occur naturally pretty easily. So introducing whitespace clobbering on `{% # comment only tags %}` feels safe enough.

**Comment by samdoiron** [comment]
> Using {# comment #} also allows syntax highlighting to easily pickup on a whole block of comments.

This is just as easy with `{% # this syntax %}` since tags can span multiple times. For example:

```liquid
{% # This is what
a multiline comment would look like.
```

> I never understood why whitespaces in control tags were a thing. Having 80+ white lines where a for used to be adds nothing but extra payload to the resulting document. They should all eat whitespaces by default.

Totally agree, especially in this case. From memory this might be as simple as defining `blank?` to return true on the node.

**Comment by CalinR** [comment]
> I agree on the {% # , the reason why {# is not viable is because it will break inline CSS. E.g: @media(...){#mydiv will break the parser.
Excellent point. This point alone is good enough to rule out the `{#` syntax and instead go with `{% #` to avoid conflicts like this.

> #This is just as easy with {% # this syntax %} since tags can span multiple lines. For example:
Good point, this seems like a non issue then.

**Comment by isAdrisal** [comment]
Definitely agree with @samdoiron on `{% # this syntax %}`.

Less certain that eating whitespace should be the default behaviour. Two main concerns:

- It's not the standard behaviour of other Liquid tags.
- It can cause unexpected HTML-breaking issues in certain situations. One example:

**Liquid:**
```
<video class="foo"
  autoplay
  {% # a comment explaining next line %}
  muted
  src="bar.mp4"
></video>
```

**Invalid output (with auto whitespace removal):**
```
<video class="foo"
  autoplaymuted
  src="bar.mp4"
></video>
```

**Desired output:**
```
<video class="foo"
  autoplay
  muted
  src="bar.mp4"
></video>
```

Changing `{% #` to `{%- #  -%}` when typed should be left to IDE shortcuts and user preferences imo.

**Comment by CalinR** [comment]
I could be wrong, but my understanding is that the way whitespace control currently works is that the output would actually be what you showed in the desired output. It should act the same as a {%- where it would just remove the line that the code block was on and not remove the line break before it.

**Comment by isAdrisal** [comment]
Perhaps I've misunderstood how this will behave differently to `{%- comment -%}{%- endcomment -%}`.

Currently, this input:
```
<video class="foo"
  autoplay
  {%- comment -%}A comment{%- endcomment -%}
  muted
  src=""
></video>
```

gives this output:
```
<video class="foo"
  autoplaymuted
  src="bar.mp4"
></video>
```

**Comment by CalinR** [comment]
You are 100% correct. Sorry I don't know why I thought it behaved that way. I just tested it out myself too. I agree, that is a bit weird and I guess my misunderstanding shows that people would probably run into that problem often if that was auto assumed.

You're probably right with having it be controlled by the user instead unless the behaviour was changed specifically for this instance. I feel that this would also produce unexpected results as well.

**Comment by samdoiron** [comment]
>  are 100% correct. Sorry I don't know why I thought it behaved that way.

I think the assumption that tags don't change data outside of their bounds is the sane one. I can imagine the reasoning for it being to remove extra lines that exist only for comments. But it's definitely weird. 

I don't think anyone would want _that_ behaviour of `{%-` to be the default for comments.

The behaviour I would expect for a comment is that everything from the opening `{` to the closing `}` is striped out entirely. The `{%-` syntax seems to 
This may be possible without differing too much from existing behaviour.

**Comment by isAdrisal** [comment]
> The behaviour I would expect for a comment is that everything from the opening `{` to the closing `}` is striped out entirely. The `{%-` syntax seems to

Would that be similar to the current `{% comment -%}{%- endcomment %}` behaviour, with whitespace only removed for the inside edges of the tags?

> This may be possible without differing too much from existing behaviour.

I don't feel especially strongly about this, but I am generally not in favour of creating new edge cases where certain language rules/behaviours don't apply. Given not stripping whitespace is the default for all other Liquid tags, I'd prefer it be the default here also and `{%-` syntax is always available to change that based on preference.

**Comment by nickpearson** [comment]
I don't have a strong opinion on this, but I'll add some notes about my decision process when adding support for Liquid comments in my own app (which has a preprocessing step to remove such comments before strings are parsed with Liquid).

I use `{# ... #}`, which I chose so that comments have an ending ( `#}` ) that is distinct from Liquid's tag ending ( `%}` ).

This means comments can contain any sequence of characters (other than `#}` of course), including Liquid tags, allowing them to be used for commenting out sections of Liquid code (including incomplete code that would break the parser if `{% comment %}...{% endcomment %}` was used).

As far as `{#` occurring naturally in code (as [noted](https://github.com/Shopify/liquid/issues/1393#issuecomment-770268430) above), it's less likely the code will also contain `#}` to end the comment. Without a matching ending, the `{#` sequence can just be left alone (which is how my app handles it, for this very reason).

**Comment by Ironskink** [comment]
I'll throw my support in for the `{% # Comments! %}` (and `{%- # Stripping comments! -%}`) syntax as well. The basic tag should do the same non-stripping of whitespace that existing tags do. Whitespace stripping is great for blocks but can do weird stuff when used in the middle of a line or HTML tag, and as an inline comment is well-suited to being in either of those places I vote that the whitespace control should be left for the author to decide.

**Comment by duncan** [comment]
> I think the assumption that tags don't change data outside of their bounds is the sane one. I can imagine the reasoning for it being to remove extra lines that exist only for comments. But it's definitely weird.

While the big swathes of empty space from the default whitespace behavior (as with ERB) always makes my eyes jump, I agree with @samdoiron. I’d keep this change as narrow as possible and just introduce `#` as a comment char to EOL, leaving the behaviors of the `{%...%}` and `{%-...-%}`tokens as is. At least until you’re ready to bundle it in with other breaking changes that would be net usability improvements.

**Comment by ADTC** [comment]
I fully support this! Please implement. Writing comments in Liquid is the most cumbersome way of comment-writing that I ever encountered. (And once I thought `<!--` HTML comments `-->` are weird!) It's so natural to use `//` and `/* */` but they scream JavaScript/CSS to me (plus writing them mixed with Liquid would be a readability nightmare), so **`#` is the perfect comment character in Liquid**.

My idea would be to use the `{}` with the `#` because the curly brackets already have a meaning in Liquid. It agrees with @nickpearson as well as @samdoiron and it expands further:

`{% ..... %}` - processing tag _opener and closer_
`{{ ..... }}` - output tag _opener and closer_
`{# ..... #}` - multi-line comment _opener and closer_
`{#} ... EOL` - single line comment _indicator (see note below)_
`# ..... EOL` - single line comment _tag_ (for use in `liquid` tag **only** as a shorthand for `{#}`)

**Example:**
```
{% if awesomeness == 'awesome' %}
  {#} this is an awesome single-line comment
  {# an awesome
     multi-line
     comment
     {# with
        a nested
        comment
     #}
  #}
  {% liquid
     # here's some awesome liquid code below!
     assign awesomeness = 'more awesome'
     if likes > 5 or hearts > 2
       assign awesomeness = 'even more awesome'
     endif
     {# the multi-line comment tag is so awesome
        that it {# even works inside #} the liquid tag!
     #}
  %}
  <i>an awesome text with some {{ awesomeness }}</i>
{% endif %}
```

**Pseudo code logic is simple!**
* Where Liquid already looks for `{%` and `{{`, add one more case to look for `{#`.
* If found, then check the next character right after that.
* If that's a `}` ignore everything until the end of line.
* If not, then look for the closing `#}` and ignore everything in between.
  * Also look for `{#` that comes first (but skip `{#}`), then recursively look for both `{#` and `#}` until all nested comments are closed. This allows commenting out huge blocks of Liquid code for testing.
* Inside `liquid` tag, have a logic looking for `#` or `{#}` as a tag anywhere within the Liquid code and if found, ignore everything until EOL
  * Also look for nested multi-line comments inside the `liquid` tag using the exact same logic as those outside.

This to me would be the perfect way to introduce real comments. It gels very well with standard programming practice, and it fully agrees with how everything else is currently implemented in Liquid. It also won't break any existing Liquid code (to the best of my knowledge). I don't know any other language that has a processing keyword (tag) like `comment` other than [the infamous `REM`](http://www.gavilan.edu/csis/languages/comments.html) simply to mark comments. They just use special characters like `//`, `#`, `/* */`, etc. so `{#}`, `#` and `{# ... #}` would perfectly align with this standard.

**Whitespace Control**
Just like other openers and closers, the multi-line comment opener and closer would support white space control using `{#-` and `-#}`. The single line comment indicator `{#}` should be whitespace stripping by default (towards the left only, not after EOL), and won't have any hyphenated form.

**Why is the single line comment indicator `{#}` and not `#`?**
I chose to use `{#}` to indicate single line because using `#` as an indicator would be a **breaking change** and it departs from the established norm that all Liquid code is enclosed in `{}`. I also won't use `{#` because then the parser has to look for the multi-line closer `#}` then go back and look for EOL when it doesn't find one. This is extra unnecessary work and makes the logic more complex. (Same reason why `// ... //` doesn't exist. Also, syntax highlighters would be confused where the closing `}` is.)

**PS:** The link on _"the infamous REM"_ is a great read about the history of programming comments. Be sure to read it! _(Should I add a mega-comment?)_

@dylanahsmith I took like an hour or two writing this, and then I saw your PRs being referenced here. I hope you'll take a look and see if this is a good idea and it can be implemented.

**Comment by dylanahsmith** [comment]
@ADTC anything outside of `{{`...`}}` and `{%`...`%}` tags could be a breaking change, since it would change the meaning of that from being text to comment.  An example was even given for how using `{#` to start a comment would be a breaking change for inline CSS (e.g. `@media(...){#mydiv`).

**Comment by ADTC** [comment]
@dylanahsmith the simple solution to that would be to find some other obscure character that wouldn't break something else. For example, would `~` work? As in, **`{~ a multi-line comment ~}`** and **`{~} a single line comment`**? (We can still keep `#` inside liquid code if that's preferred, but for consistency, I'd rather use `~` as in **`~ a single line comment inside liquid tag`**.

Everything else in my post would be exactly the same. Just replace `#` with another character.

**PS:** Updated the post with an image showing possible syntax highlighting.

**Comment by samdoiron** [comment]
> “A good idea is something that does not solve just one single problem, but rather can solve multiple problems at once.”
> – Shigeru Miyamoto

I love the aesthetics of the `~` comment system @ADTC described, but I feel like there may be a more general solution hiding in it. I see three advantages in it over my initial single-tag proposal. 

1. `{~ ... ~}` Can be used across multiple lines within a Liquid tag
2. `{~}` Can be used to comment a single line without the closing `%}`
3. `{~}` and `{~ ~}` contain fewer characters than `{% # }`, and less visual noise.

I think points 1 and 2 symptoms of a more general need. If we consider `#` to be a tag, then the what we really want is _single-line liquid tags_ and _multi-line tags within liquid blocks_. Here's a proposal that attempts to unify them:

```
{% # add the hash character as a new tag %} 
{% # so all of the
   # ways of using it we've discussed %}
{% liquid
  # continue to work
%}
```

but also (point 2)

```
{~} # Add {~} as a new way of invoking the Liquid tag, which reaches to the end of the line
{~} assign greeting = "hello" | append: " world"
{~} if foo == 10
   ...
{~} endif
```

and (point 1)

```
{% liquid 
  # Add the ability to wrap lines within Liquid blocks by using
  # the standard brackets
  if foo == 123
     {% assign bar =  "yes"
      | append: " please" %}
  endif 
```

Bonus:

```
{~
  # Perhaps, when expanded, this tag
  # acts the same as a liquid block
  if foo == bar
    echo baz
  endif
~}
```

What remains is that the syntax is still a bit longer and more noisy in some cases than the comments proposal, eg

```
{~} # This syntax
vs
{~} This syntax
```

But I think the flexibility benefits would be worth it.

**Comment by samdoiron** [comment]
@ADTC Upon investigation, a number of existing Liquid templates already use `{~` in their templates, likely to perform front-end templating afterwards.

**Comment by ADTC** [comment]
> a number of existing Liquid templates already use `{~`

@samdoiron I see. I haven't seen that syntax in Shopify but I understand Liquid is used in many different places.

Regardless, **my proposal isn't to use `#` or `~` specifically,** but to take any viable unused character or a phrase of characters and apply the **concept** of using it for comment demarcations. I'm mainly proposing the concept there, but the tool for implementing it can be changed to a better tool. Let me call that **Concept 1** because I also had my mind run wild now with...

# Concept 2

Taking the original idea here that proposed the use of a `#` tag in this format `{% # ... ... ... %}` we can expand it further to allow multi-line comments similar to how the `{% liquid ... ... ... %}` tag allows multi-line code inside it.

Single-line or Multi-line real-text comments within other languages (like HTML) can be:

    {% # comments that are single-line or multi-line, it doesn't matter because it's always closed with %}
    
    {% # the exact same construct above
        makes multi-line comments (real text ones, not disabled code)
        possible similar to multi-line code in liquid tag %}

Disabling code can be done using a different multi-line syntax that makes use of a **dynamic closer**. This allows the programmer to use any phrase (within the syntax rules of a variable name) as a demarcation unit.

    {% #thiscodeneedswork
        multiline comment syle that disables {% code %}
        with the optional dynamic closer
        note that any %} before the repeated closer below won't have an effect,
        making it incredibly useful to disable code
        but a %} that comes after the repeated closer will close the comment.
        the code can even have other multi-line comments embedded because they are all ignored:
          {% #i_disabled-this_code_2_years-ago
              old disabled code
          #i_disabled-this_code_2_years-ago because it wasn't working %}
    #thiscodeneedswork ... there can be more text here
        because the comment actually closes after the repeated closer with %}

The use of a dynamic closer would completely bypass the problem of nested comments since the programmer can define any random string of characters as a closer as long as it's reasonably sure it's not already used somewhere in the disabled code.

And here's how to write comments in `liquid` tag. Due to the way code is written inside this tag, the only way to add multi-line comments would be with a dynamic closer (but this becomes really useful to disable chunks of code).

    {% liquid
        # a single-line comment
        # another single-line comment
        code
        code
        #debugging2021feb
            a multi-line comment and
            possibly even some
            disabled code here
        #debugging2021feb
    %}

In order to avoid the potential pitfall of misunderstanding the first word of a comment as a dynamic closer, the following must be mandatory for dynamic-closer-based multi-line comments.

First, the line with dynamic closer can only have unlimited spaces after the closer declaration but anything else would be a syntax error. For example:

    {% #Accidentally writing a single-line comment misunderstood as dynamic closer. %}

would throw a syntax error _"Found unexpected text `writing ...` after comment closer declaration `#Accidentally`"_ prompting a fix by either adding a space after `#` or by breaking `writing ...` into a new line.

Second, the closing repetition of a dynamic closer must be mandatory, and this style of multi-line comment cannot be left wide open until the end of file, and it shouldn't be assumed that only a `%}` would close the comment without the repetition.

**Note:** Whitespace control is as usual, with `{%-` and/or `-%}` whenever it is needed.

**PS:** In the demonstration code blocks above, spaces were added at the beginning of lines to make it clear. As with any Liquid code, it's not mandatory to indent anything.

**Comment by timdmackey** [comment]
If comments are to going be implemented as a tag, ie:
```
{% liquid
  # this is a comment
  echo “hello world”
%}
{% # this is a comment %}
```
Is there any reason why they couldn’t also be a first-class tag which allows block comments? ie:
```
{% # 
  This is a block comment
  with multiple lines of text
  about some feature
  I want to document. 
 %}
```
The `{% comment %}` tag is cumbersome in any use case, it would be nice to make it entirely redundant.

**Comment by timdmackey** [comment]
Or at least allow something like this:
```
{%
  # This is a block comment
  # with multiple lines of text
  # about some feature
  # I want to document. 
 %}
```

**Comment by timdmackey** [comment]
I just finished reading this thread and the existing pull request for the _**third time**_. I may have been misunderstanding how the pull request is implementing this. I _**think**_ that both examples I gave will work with the currently proposed pull request, but I'm not sure...

I guess my confusion is over the question of whether the hash comment will eat text until the EOL, or until the tag is closed with a `%}`. The `liquid` tag is new to me, so i'm not sure if it works the same as regular tags. With regular tags, arguments can be split over multiple lines. Since the `liquid` tag doesn't have a closing `%}` delimiter, does that mean that all tags operate only on a single line? If so, I would suppose this to mean that a `#` tag inside of a `liquid` tag inherits the single-line behavior, ie. only operating until the EOL, while `#` as a standalone tag would inherit multi-line behavior of standard tags, allowing us to have a block quote with only one `#` symbol at the beginning.

**Comment by dylanahsmith** [comment]
> I guess my confusion is over the question of whether the hash comment will eat text until the EOL

The direction pull request #1401 is taking is to have the comment end at the end of the line.  That way you will be able to precede a tag with a comment.

I would also like the to be able to split a tag into multiple lines and comment on a specific part of it (e.g. an argument or a filter in a filter chain).  However, this along with comments after a tag brings a risk of introducing backwards incompatible changes, so application defined tags will need to be changed to support this.  Starting a comment at the start of a tag avoids these backwards compatibility concerns, so this is the only way in which a comment is like a tag.

**Comment by charlespwd** [comment]
Bringing some context from the [VS Code Language Configuration](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#comment-toggling) world:

We don't have a syntax for lineComment and those should be a set of characters that turn the rest of the line into a comment. 

What about `{#}`? Feels kind of OK to type. Fits with the ruby comment syntax a little bit. Isn't valid CSS or JS or HTML (that I know of).

```liquid
{#} Here we iterate over all products
{% for p in all_products %}
   {#} Here we turn those products into images
   {{ p | img_tag }}
{% endfor %}

{#} This script is parser-blocking but there's no way around it. So we disable the theme-check rule for it. 
{#} theme-check-disable ParserBlockingJavaScript
<script src="blocking.js"></script>
{#} theme-check-enable ParserBlockingJavaScript
```

And we can keep the `#` shorthand for liquid blocks.

**Comment by ADTC** [comment]
I suppose if we open this up for discussion, then everyone will have their own weird ideas that make sense only to them based on their own experiences.

Let's see what the final decision will be. I'd be happy enough so long as it's prettier than the clumsy `{% comment %} ... {% endcomment %}` 😄 

@charlespwd that actually sounds good enough 🙂

**Comment by eballeste** [comment]
<img width="642" alt="Screen Shot 2021-12-14 at 3 24 11 PM" src="https://user-images.githubusercontent.com/6924108/146073952-dd633e9c-fb10-49b2-9550-facf964825b9.png">

**Comment by eballeste** [comment]
<img width="649" alt="Screen Shot 2021-12-14 at 3 26 49 PM" src="https://user-images.githubusercontent.com/6924108/146074498-cb01b59a-56bd-4601-92bb-3c7aef8c8dbb.png">

**Comment by Benecke** [comment]
There's a bug with the current implementation. The parser tries to execute `comment` and `liquid` when it's written at the beginning of a new line like this:

```
{%- liquid
  comment
    cool, i'm writing a 
    comment
  endcomment
-%}
```

throws: **Liquid syntax error (line 4): 'comment' tag was never closed**

```
{%- liquid
  comment
    cool, i'm writing liquid stuff
  endcomment
-%}
```

throws: **Liquid syntax error (line 4): Unknown tag 'stuff'**

**Comment by dylanahsmith** [comment]
@Benecke that isn't a bug, it is parsed (not executed) in that way to support nested comments.  Some other languages have the opposite problem where trying to nest the comment results in the comment ending prematurely.  If you really want to put garbage inside the comment, then you can use the raw tag for that purpose.

**Comment by Benecke** [comment]
@dylanahsmith

> Some other languages have the opposite problem where trying to nest the comment results in the comment ending prematurely.

Well it looks that's exactly what's happening here with liquid.

I'm not trying to nest comments. I'm trying to write a sentence where I use manual break after 80 characters (vertical line in my editor). This manual breaks puts the word `comment` at the beginning of the line and this produces the error. It's not the word `comment` per se. It's the position, as I wrote.

**Comment by eballeste** [comment]
it's fine if you use my double quote approach, pardon my ignorance but is my suggestion not a good one? I'd like to learn why not if it isn't

<img width="196" alt="Screen Shot 2021-12-15 at 11 59 13 PM" src="https://user-images.githubusercontent.com/6924108/146310972-d0ce0e7d-43de-4c12-9146-8e49da46977b.png">

**Comment by dylanahsmith** [comment]
This was implemented in https://github.com/Shopify/liquid/pull/1498 which is available to use in Shopify now.
