### ISSUE TITLE
Documentation: increment and decrement tags should mention that they will echo the new value

### ISSUE THREAD

**Issue by ADTC** [Shopify/liquid#1399]
_(I'm not sure how to contribute documentation updates. There's no word about it inside `CONTRIBUTING.md`)_

The `increment` and `decrement` tags are special in that they would output or echo the variable's final value onto the page (or whatever output sink you're using). This is not mentioned in [the documentation](https://shopify.github.io/liquid/tags/variable/#increment), and I think it should be. It isn't clear that these tags are echoing tags. They look and sound just like the silent tags like `assign`.

**Comment by dylanahsmith** [comment]
The documentation is on the gh-pages branch.  :+1: to updating the documentation and CONTRIBUTING.md to clarify both of your points.

**Comment by ADTC** [comment]
For documentation updates, I can skip these I suppose:

* If it makes sense, add tests for your code and/or run a performance benchmark
* Make sure all tests pass (`bundle exec rake`)

**Comment by dylanahsmith** [comment]
Right, tests and benchmarking are only relevant to code updates

**Comment by dylanahsmith** [comment]
Fixed by #1405

**Comment by ADTC** [comment]
I'm working on the documentation change. Does this apply to the `{% cycle %}` tag as well? And what other tags do this? Can't remember.

TBH, all these tags behaving this way is actually unexpected behavior to me. I don't understand the rationale, and I had expected `{% %}` to do only processing (no output without `echo`), and `{{ }}` to do only output (no processing except filters). But it's already set in stone, and we can't change it now (except by deprecating it and introducing a _new_ keyword).

It raises the question: what happens if I use `increment` inside a `{% liquid %}` tag?

**Comment by dylanahsmith** [comment]
It's strange that the [cycle tag documentation](https://shopify.github.io/liquid/tags/iteration/#cycle) is listed among the iteration tags.  However, it does say "Each time cycle is called, the next string argument is printed."  The word "printed" might be confusing to non-programmers, but it hasn't omitted that it outputs the value.  It also does mention the common use case "applying odd/even classes to rows in a table."

Tags like `cycle` and `increment` aren't really necessary, since the same could be done using assignments, filters (`plus`) and index lookups.  So I think their purpose was to be a convenience for common templates tasks, although I'm not sure if the `increment` tag is actually commonly used, so these decisions might not be ideal in hindsight.

> TBH, all these tags behaving this way is actually unexpected behavior to me. I don't understand the rationale, and I had expected `{% %}` to do only processing (no output without `echo`), and `{{ }}` to do only output (no processing except filters).

Looks like the introduction could be improved, since it does say

> Tags create the logic and control flow for templates.
...
> The markup used in tags does not produce any visible text.
...
> Tags can be categorized into three types:
> * Control flow
> * Iteration
> * Variable assignments

which does seem to set the wrong expectations that tags don't directly output anything.

That list also seems to exclude a couple of categories that are in the sidebar: "Comment" and "Raw".  Although, those seems like overly specific categories that are really just for single tags.

Note that you could think of the `{{ ... }}` as being a shortcut for `{% echo ... %}`.  Although, the echo tag was only added for use in the liquid tag.

> It raises the question: what happens if I use `increment` inside a `{% liquid %}` tag?

The liquid tag doesn't change the behaviour of any tags, so they will still output if that is their purpose.

**Comment by ADTC** [comment]
> wrong expectations that tags don't directly output anything.

In all the programming languages (and even in templating languages like JSP and PHP) that I came across, it's the right expectation that random keywords don't output anything right after doing something else. The outputting is always done through specific mechanisms that are clearly intended _solely_ for outputting. Other processing mechanisms do not output unexpectedly - they just process.

So it's certainly very odd that the Liquid language has tags that do something _and then_ output something. I'd motion for these tags of "convenience" to be **deprecated** since they don't _just_ do what it says on the tin - they have hidden behavior. Example: `increment` should only just increment the given variable, nothing else. If it's going to output too, it should really be `increment_and_echo`. 🤷

**Comment by dylanahsmith** [comment]
The sole purpose for the cycle and increment tags is outputting.  It isn't some hidden behaviour, it is just the behaviour of the tags and sole purpose of these tags.  

Deprecating a feature that we aren't going to remove, to avoid breaking existing templates, without recommending a better way to do something won't do any good.  So it doesn't really make sense to deprecate convenience features if they are actually convenient.

**Comment by ADTC** [comment]
Fair enough 🙂 it just needs clearer documentation then. 😄
