### ISSUE TITLE
Unexpected `{% break %}` and `{% continue %}`

### ISSUE THREAD

**Issue by jg-rp** [Shopify/liquid#1618]
Consider this template..
```liquid
{%- if true -%}
  before
  {%- if true -%}
    hello{% break %}goodbye
  {% endif -%}
  after
{%- endif -%}
{% for x in (1..2) %}
  {{ x }}
{% endfor %}
{% for y in (3..4) %}
  {{ y }}
{% endfor %}
{% for z in (5..6) %}
  {{ z }}
{% endfor %}
```

I had initially assumed the `{% break %}` tag would result in a syntax error, just like we get with an unexpected `{% else %}`. However, having noted the updated tests in commit f4fa0ff, we get the following output.

```plain
beforehello
```

Two things surprised me about this result. The first is that we don't see `after` in the output. The interrupt seems to step over the remainder of the parent `if` block too. The second is that none of the subsequent `{% for %}` loops render anything.

Please could you tell me if this behaviour is intended or a bug? 

Many thanks.

**Comment by dylanahsmith** [comment]
I'm not sure if it was originally intended, but it is behaviour that is tested (https://github.com/Shopify/liquid/blob/v5.4.0/test/integration/tags/break_tag_test.rb#L8-L16) and preserved for backwards compatibility.  However, I also don't think you should depend on liquid quirks like that, which will make your liquid code harder to understand and maintain.  Ideally, we would detect and warn about issues like that, since I would expect that it isn't the liquid author's intention to leverage that quirk and debugging the template bug is harder without a warning or error.
