### ISSUE TITLE
Templates that use `assign` / `capture` tags are thread-unsafe

### ISSUE THREAD

**Issue by UlyssesZh** [Shopify/liquid#1754]
```ruby
require 'liquid'
Liquid::Template.register_filter Module.new { def s(input) = sleep(input/10.0) && input }
template = Liquid::Template.parse '{% assign u = v %}{{ u | s }}{{ u }}'
3.times.map { |i| Thread.new { print template.render! 'v' => i } }.each &:join
```
Expected output: `001122`; Actual output: `021222`.

Why I found this: https://github.com/jekyll/jekyll/issues/9485#issuecomment-1797873978

**Comment by ianks** [comment]
I think this happens because certain state for a `Liquid::Context` will be re-used when a hash passed in to `Liquid::Template#render`. If you want to avoid that behavior, it is best to explicitly create a new `Liquid::Context` for each render invocation, i.e.:

```ruby
template.render!(Liquid::Context.new("v" => i))
```

**Comment by ioquatix** [comment]
`Liquid::Template` does not look thread-safe at all.

Re-using `Liquid::Template` looks unsafe in general, it's design appears to capture lots of "per-render" state, e.g. `template.freeze.render!` fails.

As per the above discussion,

```
      when Hash
        Context.new([args.shift, assigns], instance_assigns, registers, @rethrow_errors, @resource_limits)
```

When a hash is provided, a context is created using `self.assigns`, which is a per-template cache of assignments. So naturally, this state leaks. An even more simple example:

```ruby
template = Liquid::Template.parse '{% increment u %}'

> template.render!
=> "0"
> template.render!
=> "1"
> template.render!
```

The suggestion to use a context does appear to work:

```ruby
context = Liquid::Context.new

> template.render! context
=> "0"
> template.render!
=> "5"
> template.render! context
=> "1"
```

However, I think this kind of default (thread unsafe) mutable behaviour is extremely unsafe, because without understanding the details of the implementation, it's easy to get wrong and the impact of "getting it wrong" is likely to be a security issue. I would highly recommend that the `render` call does not mutate the template. In other words, even this still fails:

```ruby
template.freeze.render!(context)
```

The [example in the `readme`](https://github.com/Shopify/liquid?tab=readme-ov-file#how-to-use-liquid) is likely to be a security issue for any non-trivial template. Specifically because it uses `@template` which implies some kind of instance variable which could have a life-time spanning several requests. Reusing state like this can and [does lead to security issues](https://yhbt.net/unicorn-public/20210312094129.GA14538@dcvr/).

If there are issues adopting a more secure approach, I suggest you have users explicitly opt into the legacy behaviour, e.g. `Liquid::Template.new(mutable: true)`. Also, lazy initialization of `@registers`, `@assigns` and so on is also not thread safe. Therefore, there is no way to share an instance of `Liquid::Template` safely between threads. If that is intentional, I'd strongly consider enforcing this, e.g. `raise ... unless @thread == Thread.current` in `render`.
