### ISSUE TITLE
Ternary operator support

### ISSUE THREAD

**Issue by Pym** [Shopify/liquid#236]
Hello!

I think it would be awesome to implement ternary operator support [like Twig does](http://twig.sensiolabs.org/doc/templates.html#logic):

```
{{ foo ? 'yes' : 'no' }}

{{ foo ?: 'no' }} == {{ foo ? foo : 'no' }}
{{ foo ? 'yes' }} == {{ foo ? 'yes' : '' }}
```

**Comment by fulldecent** [comment]
Here is the use case:

`<h1>REPLACE ME</h1>`

Filling in by finding the first available:

  * `page.heading`
  * `page.title`
  * `site.title`

**Comment by TWiStErRob** [comment]
Here's another one:
```
{% assign postCount = site.categories[other_category.slug].size %}
{% unless postCount %}{% assing postCount = 0 %}{% endunless %}
Versus
{% assign postCount = site.categories[other_category.slug].size ?: 0 %}
```

**Comment by carolineschnapp** [comment]
I find Ternary operator construct unnecessarily hard to read in Liquid. To me anyway, Liquid is not a programming language, it is meant to be super simple. I am all for making Liquid do things that were not possible before, when these things are most needed, but since Liquid can do in a more verbose ( in my opinion easier to read ) way what a Ternary operator would allow, then this would make me give a :-1: .

**Comment by ajwhite** [comment]
>To me anyway, Liquid is not a programming language, it is meant to be super simple. 

Correct, but when you can make assignments, it would be nice to have decent support in that. Nothing crazy, but something like a ternary makes an assignment based on a condition a lot easier to write.

>I find Ternary operator construct unnecessarily hard to read in Liquid.

I disagree, using @TWiStErRob's example, i think
```
{% assign postCount = site.categories[other_category.slug].size ?: 0 %}
```
reads pretty easily. It feels a lot easier to read than
```
{% assign postCount = site.categories[other_category.slug].size %}
{% unless postCount %}{% assign postCount = 0 %}{% endunless %}
```


>but since Liquid can do in a more verbose ( in my opinion easier to read ) way what a Ternary operator would allow

I guess that comes down to personal preference. I, personally, don't think multi-lined assignments due to verbosity is easier to read. Being used to ternaries, it feels like extra work to understand the assignment by having to read multiple lines of conditional reassignments.

**Comment by TWiStErRob** [comment]
> I guess that comes down to personal preference.

I think this is key here, `liquid` is a framework/library. How one uses a library is their problem. But if a library lacks a feature that's everyone's (at least those who want to use it).

I could also argue for `size` to return `0` when the object is `null`, but that's a different issue.

**Comment by TWiStErRob** [comment]
Hmm, lookey here, it's not ternary, but at least Elvis is alive! (added in #267)
[`{% assign postCount = site.categories[other_category.slug].size | default: 0 %}`](https://docs.shopify.com/themes/liquid-documentation/filters/additional-filters#default)
I just wish GitHub pages/Jekyll would bump to 3.x...

**Comment by ajwhite** [comment]
Nice, even an "Elvis operator" is a nice step up. Would still be nice to have a true ternary, but this is a good find

**Comment by pjmay** [comment]
@fredryk you can simplify it even more:
```
<div class="{% unless product.available %}un{% endunless %}available">
   .. content ..
</div>
```

**Comment by Dorian** [comment]
:+1: for ternary operators, assignments are much more complicated without it.

**Comment by bbuie** [comment]
This is a good reason why Shopify hasn't become the clear leader in ecommerce. They think supporting developers is not in their best interest. Unfortunately, they don't realize the power of a strong recommendation from a developer to a potential customer.

**Comment by nickpearson** [comment]
Yes, because they do not implement every single requested feature in an excellent library they make freely available to everyone, Shopify hates developers.

Sure, ternary operator support would be great, but your claim is unreasonable and way out of proportion. And if I remember correctly, they do accept pull requests.

**Comment by bbuie** [comment]
I just re-read my comment and it did sound a bit harsh. :(

That said, the only reason I know Liquid is because they require it to build their themes. I'm a customer myself, and I've developed themes for many of their customers, so don't think I'm using a free library and then complaining.

In addition, this is just **one of the many examples** where it is clear that shopify ignores requests even with a need. This isn't helping them become a clear leader. 

I've been developing ecommerce sites for almost a decade and continue to have a high hope that someone will emerge as the leader. I really thought Shopify would, and it has a lot going for it, but I can see they're missing the opportunity to cater to developers and thus grow their market share.

**Comment by fw42** [comment]
Thanks for sharing your opinion, and I understand your frustration, but this GitHub repository is not the right place to discuss this. This is for discussions around the Liquid open source Ruby library, not about Shopify the company or Shopify the product (or even Shopify's use of the Liquid library).

**Comment by bbuie** [comment]
You're right. Sorry about that. I got carried away.

**Comment by ajwhite** [comment]
We've had discussions above related to how this can be done with the existing support
```
class="{% if foo %}foo{% else %}bar{% endif %}"
```

This _works_. It's not beautiful, but it does support the use case.

@fw42 has made it clear that the maintainers are not likely going to introduce this feature. But we should keep in mind that this is an open source project with a lot of contributors. I'm sure the project maintainers would be happy to look at a contribution introducing this support, but this has been closed because it's not on _their_ development road map. No reason we can't put forward a solution as a community contribution to the project.

**Comment by ajwhite** [comment]
Although I believe @bbuie's criticism is likely due to the original reason the issue was closed

> Not a big demand for this at Shopify. Sorry.

In contrast to 

> This is for discussions around the Liquid open source Ruby library, not about Shopify the company or Shopify the product (or even Shopify's use of the Liquid library).

**Comment by bbuie** [comment]
@ajwhite that is correct. 

The reason I was hoping for this is I need to do something like this:

`{% assign is_true = vav < 0 ? true : false %}`

Is that possible another way? I hate to write 5 lines of code for something that should take one. Less code = less bugs. :)

**Comment by ajwhite** [comment]
Yes, even simpler without a ternary :wink: 

```
{% assign is_true = vav < 0 %}
```

`vav < 0` is either `true` or `false`

Unless you're just describing a simplified example where you wouldn't be using booleans based on the expression, something like:

```
is_something = vav < 0 ? 'not a boolean' : 'also not a boolean'
```
In which, no, it'd still have to be expressed as
```
{% if vav < 0 %}
{% assign is_something = 'yes it is' %}
{% else %}
{% assign is_something = 'no its not' %}
```

**Comment by bbuie** [comment]
@ajwhite Thanks. I tried that but it wasn't working so I went on the search. This particular project is outside Shopify, so I wonder if they're out of date.

**Comment by pushrax** [comment]
Shopify is always running the latest `master` branch of Liquid.

**Comment by bbuie** [comment]
@pushrax Thanks, that is good to know. What I meant was that the project I'm working on may not be using the latest master branch because it is a project outside of Shopify.

**Comment by pushrax** [comment]
I see, totally misunderstood you. Perhaps it is.

**Comment by lesander** [comment]
Since this has not been implemented yet, and will likely never be, the following achieves a somewhat ternary operator behaviour for variable tags.

```liquid
{{ a | default: b }}
```
The code above will print `a` if it does not equal a falsy value, and will print `b` if `a` does equal a falsy value. While this is not exactly as flexible as a ternary operator, it might suit your needs.

**Comment by jamesbeninger** [comment]
> Yes, even simpler without the unsupported ternary 😉
> 
> {% assign is_true = vav < 0 %}
> 

For the record, this won't work.  Liquid doesn't assign logical operations.  The assign tag only supports raw booleans (true or false).  Trying to `{% assign aFalseExpression = (2 == 1) %}` inexplicably assigns "2".

**Comment by Roboe** [comment]
Expanding @lesander suggestion: if anyone needs the ternary operator just to avoid `nil` and falsy values, then the below code will work for them:

```liquid
{% assign text = excerpt | default: full_text %}
```

**Comment by rbrlortie** [comment]
Are we seriously looking for use cases for something that is considered a default feature in most templating languages? E.g. Twig has had ternary operators since Jan 8, 2013. Sure, there are alternatives but there are always alternatives in software development. 

Thanks @nickpearson for this snippet.

**Comment by jeepchenup** [comment]
> Expanding @lesander suggestion: if anyone needs the ternary operator just to avoid `nil` and falsy values, then the below code will work for them:
> 
> ```
> {% assign text = excerpt | default: full_text %}
> ```

Thanks a lot. It works for me.

**Comment by james0r** [comment]
{% link.active ? 'active' : '' %}

to dynamically add a bootstrap class? would be nice.

**Comment by tmmgrafikr** [comment]
What is the status on this issue, since it hasn't been closed?
Would love to see this feature be implemented!

**Comment by adamndev** [comment]
+1

**Comment by knynkwl** [comment]
+1

**Comment by torian257x** [comment]
makes me frown a bit. The push back against taking liquid out of stone age seems unreasonable. The argument "shopify doesnt care"

well, I don't know man, the consumers of your liquid template language are the shopify developers. The ones that create apps and themes for you, you know? the ones who spent hours and hours working with the templates.

But you cannot create arrays in liquid, or assign conditions, or use ternary operators.  Sticks and stones.

If this is the branding you want for your developer community, and your company, well that is your choice.

**Comment by TWiStErRob** [comment]
> Can I make this code shorter or prettier? If possible, how can I do it?

@notrealdev shorter: no, prettier: yes

_This is only using current state of Liquid, I totally see and agree how ternary would help here and in many other cases._

```liquid
{% capture header_tag %}{% if section.settings.enable_sticky_header %}sticky-header{% else %}div{% endif %}{% endcapture %}
{% capture header_extra_classes %}{% if section.settings.show_line_separator %} header-wrapper--border-bottom{% endif %}{% endcapture %}
<{{header_tag}} class="header-wrapper{{header_extra_classes}}">
    ...
</{{header_tag}}>
```

Notice the added benefit of not having to duplicate the tag's condition at the end.

**Comment by notrealdev** [comment]
@TWiStErRob So pretty, thank you!

**Comment by TWiStErRob** [comment]
@fw42 re https://github.com/Shopify/liquid/issues/236#issuecomment-22038311, considering the amount of continued interest, the accumulated reactions on this ticket and on https://github.com/Shopify/liquid/issues/1264, and also all the comments and their reactions too, would you reconsider reopening and implementing this in the future?

**Comment by paulshryock** [comment]
Ternary operator support in liquidjs would be super useful.

**Comment by OleSkaar** [comment]
> 

Came here while looking for this exact thing :D

**Comment by nicklocicero** [comment]
The most problematic thing I can see about introducing ternary operators is that a lot of designers make Shopify themes in Liquid and don't know a lot of code. For loops are scary enough. If developers start putting in a lot of weird operations, it may scare away the designers from using the language, which is most advantageous to Shopify's growth.

**Comment by james0r** [comment]
> The most problematic thing I can see about introducing ternary operators is that a lot of designers make Shopify themes in Liquid and don't know a lot of code. For loops are scary enough. If developers start putting in a lot of weird operations, it may scare away the designers from using the language, which is most advantageous to Shopify's growth.

Sacrificing ease and terseness of code for a vast number of Shopify theme developers (this is their job and they are growing and do it everyday) for the purpose of making life easier for designers who are stepping into a territory outside their expertise in a pinch seems absolutely silly.

**Comment by nickpearson** [comment]
@TWiStErRob no, I was not aware that one could sort issues by reactions. That's pretty neat. Thanks.

I think a ternary operator would be a nice addition to Liquid, but I don't work for Shopify.

For now, I just use [a custom `if` filter](https://github.com/Shopify/liquid/issues/236#issuecomment-43118741) in my projects to approximate the syntax of a ternary.

**Comment by nickpearson** [comment]
I think we're in agreement that a ternary would be a nice thing to have in Liquid, but I don't have any control over this repository, so I'll let someone else at Shopify address your questions.

**Comment by TWiStErRob** [comment]
Ah, that Contributor tag always makes me think project owner 🤦🏻‍♂️.

**Comment by fw42** [comment]
> @fw42 @nickpearson do you know about this github feature? https://github.com/Shopify/liquid/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+ Top 2 out of 3 upvoted issues are ternary... And the top 4 are about basic language features. I think the community (your users) have voted. Did you actually interview designers, or are you assuming things about them?

I also don't work at Shopify anymore.

**Comment by MaxDesignFR** [comment]
I've been checking this thread now and then for 2 years. I use liquid nearly everyday and the lack of tenary is always a little frustrating (same for array manipulation), I'm still quitely hoping it will come true one day, even though this thread is 9 years old ah! But of course, it's not a deal breaker.

**Comment by paulshryock** [comment]
@shopify-admins possible to get some traction on this feature request?

@fw24 I see that you closed this in 2014, but don't work at Shopify anymore... any way to get this ticket reopened?

**Comment by thslang** [comment]
Please reconsider reopening this issue as such a feature would be beneficial to some and [optional] to many as it wouldn't (re: shouldn't) break existing themes.

**Comment by synsa** [comment]
Please reconsider reopening this issue as such a feature would be beneficial to some and [optional] to many as it wouldn't (re: shouldn't) break existing themes.

**Comment by notrealdev** [comment]
Can anyone create a new issue for this?

**Comment by pablogiralt** [comment]
+1

**Comment by mhraihan** [comment]
+1

**Comment by rvibit** [comment]
+ထ

**Comment by BaggioGiacomo** [comment]
+1

**Comment by lantchou** [comment]
+1

**Comment by galmis** [comment]
+1

**Comment by illia108** [comment]
+1

**Comment by yveveke** [comment]
+1

**Comment by robwatkins1988** [comment]
I must admit i am surprised this still hasnt been added.

**Comment by mryurii** [comment]
![maxresdefault](https://github.com/Shopify/liquid/assets/5550001/9765539b-f3a0-4a49-9996-699fc0bde295)

**Comment by fw42** [comment]
That comment is over 10 years old. At the time it didn't seem like there was demand. Obviously I was wrong. Unfortunately I haven't worked for Shopify in over 4 years.

**Comment by muke5hy** [comment]
I am tired of writing 
`{% if setting.foo == 'bar' %} 'hello' {% else %} 'world' {% endif %}`

I just want to do 

`{% setting.foo  == 'bar' ? 'hello' : 'world' %}`

**Comment by Mrbizzle** [comment]
> Hm I don't think we will implement this. Not a big demand for this at Shopify. Sorry.

I've been building shopify stores for a decade, trust me, there's a big demand. At least 300 developers have even downvoted your response.
