### ISSUE TITLE
Liquid 'layout' tag

### ISSUE THREAD

**Issue by joost** [Shopify/liquid#270]
Sorry. (Ab)using Github issues for a question. Searched the whole Internet for a solution. Hope you don't mind.

I saw Shopify uses a 'layout' tag (http://docs.shopify.com/themes/theme-templates/16-alternate-layouts).
Would love to have something similar in a Rails 3 - Liquid config. Any idea how? I can't seem to alter the layout option in a view (ActionView seems to determine the layout before the custom liquid template renderer does its tricks).

**Comment by kpost** [comment]
I know it's been a while since the last answer to this question, but could you clarify your solution a bit Dylan? I can't find a way to access the `context`. I have a template render method which is part of the class that is registered as a template handler with `ActionView::Template.register_template_handler`. I assume this render method is where I would set the layout for the template, but I can't access the `context` here. On the contrary, it's the place where the `context['registers']` is set (inside the liquid render), not accessed to retrieve the `context.registers[:layout]` var.

**Comment by dylanahsmith** [comment]
The liquid benchmark uses layouts, so you can see how it works here https://github.com/Shopify/liquid/blob/master/performance/theme_runner.rb#L58
