### ISSUE TITLE
Make liquid really ignore whatever is in liquid comments {% comment %}

### ISSUE THREAD

**Issue by maxheld83** [Shopify/liquid#313]
It's possible that I am just stupid (I'm a newbie), but it also appears possible that liquid (v2.5.x) doesn't ignore whatever liquid is between comments. `{% comment %}`, as documented here http://docs.shopify.com/themes/liquid-basics/logic#comment.
I get this for garbage that is between `{% comment %}` and `{% endcomment %}`:

`Liquid Exception: Unknown tag 'elseif' in _includes/_author-bio.html, included in _layouts/post.html
`

Here's my MWE:

```
{% if site.owner.avatar contains 'http://' %}
    <img src="{{ site.owner.avatar }}" class="bio-photo" alt="{{ site.owner.name }} bio photo"></a>
{% elsif site.owner.avatar contains 'https://' %}
    <img src="{{ site.owner.avatar }}" class="bio-photo" alt="{{ site.owner.name }} bio photo"></a>
{% else %}
    <img src="{{ site.url }}/images/{{ site.owner.avatar }}" class="bio-photo" alt="{{ site.owner.name }} bio photo"></a>
{% endif %}
{% comment %}{% elseif some garbage I want ignored}{% endcomment %}
```

Same stuff works fine without the last line.

My bug or Liquid's bug?

**Comment by ADTC** [comment]
Why closed? Problem isn't fixed. Why doesn't `comment` ignore everything until `endcomment` just like how `raw` does until `endraw`?

**Comment by dylanahsmith** [comment]
I guess I read the issue as asking if it was possible to ignore non-liquid text inside a comment tag and there is a `raw` tag for that purpose, which prevents that text from being parsed, so solves your problem.

> Why doesn't `comment` ignore everything until `endcomment` just like how raw does until `endraw`?

It ignores everything up until the endcomment tag, but in your case it parses `{% elseif some garbage I want ignored}{% endcomment %}` as a tag.  If your use case is actually to comment out liquid code, then you would only run into this problem when you have mistyped liquid code.

Having the comment tag behave like the raw tag would also produce the wrong behaviour for commenting out liquid code that has comment tags in it.  With your suggestion it would stop the comment at the end of the inner comment.  To avoid breaking changes, we would need to handle nested comments and nested raw tags within the comments in exactly the same way.  Even in that case, we still wouldn't have resilience to typos inside the outer comment tag, since there could be typos in the inner `raw` or `comment` start or end tags that would affect the ability to comment out that "garbage".

The purpose of the comment tag isn't to ignore garbage, it is to provide a description of the code for other people who will be reading the code, without it affecting the rendered output.

**Comment by ADTC** [comment]
I suppose then the documentation for the `comment` needs to be clear that it shouldn't be used to block out partial (open-ended) or mistyped Liquid code. The Liquid code inside the comment block (if any) should be syntactically correct and fully contained (all tags closed with their corresponding end-tags unless they self-close).

In any case I'm used to block commenting in language like Java where a `/*` has the compiler ignore everything until the first `*/`. It doesn't worry about nested block comments because it simply treats everything until that point as garbage and ignores it. It's up to the developer to deal with the nested block comments appropriately. HTML functions the same way too. So I'm quite surprised that Liquid doesn't function quite the same way and looks for nested comments in what should ideally be treated as garbage.

**Comment by sh78** [comment]
I love liquid, don't get me wrong, but this is super annoying and diverges from basically every other language. Maybe I need to improve my workflow, but very often I want to duplicate a line, comment out the original, and hack on the duplicated line while keeping the original for reference. Also commenting out loops/complex filter chains for later use is nicer than git stashing for informal projects.
