### ISSUE TITLE
Create object on the templating side?

### ISSUE THREAD

**Issue by graygilmore** [Shopify/liquid#387]
I've been creating arrays rather crudely like this:

``` liquid
{% assign array_name = 'value-1|value-2|value-3' | split: '|' %}
```

But now I'm in a situation where I'd like to create an object and have proper `key` and `value`. Is this possible to accomplish on the templating side?

**Comment by eddyparkinson** [comment]
@fw42 "Shopify forums" - please allow posts to threads marked "This post is outdated".  

Please do us small a favour. Please allow posts to threads marked "This post is outdated". "Shopify forums" has many valuable threads. Many are marked "This post is outdated", this is fine. It would be great if we could still post to such threads. So that useful info can be added to good threads.

I am guessing there is no way to port the "Shopify forums" to stackoverflow,  stackoverflow has great features.


 https://ecommerce.shopify.com/c/ecommerce-design/t/how-to-assign-an-object-in-liquid-112278#write-comment

**Comment by mymaccrack** [comment]
This is a very nice software http://bit.ly/3a9FLKv
