### ISSUE TITLE
Catch-all rescue in `escape` filter might cause issues?

### ISSUE THREAD

**Issue by nybblr** [Shopify/liquid#521]
In the StandardFilter library: https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L36-L38

The `escape` filter has had a nasty catchall rescue from the first import, but this likely breaks things (and could let unescaped code slip into the template) and is causing me issues.

What specific exception was supposed to be rescued? Happy to submit a PR to fix this if I can get some background.

**Comment by nybblr** [comment]
Related: https://github.com/Shopify/liquid/pull/259

**Comment by fw42** [comment]
yeah I agree, it's sketchy. The code is probably years old. I don't know what's being rescued there...

**Comment by fw42** [comment]
maybe it was supposed to make it not explode when you pass in something that's not a string?

@dylanahsmith @eapache ideas?

**Comment by eapache** [comment]
No idea, my best guess is the same as Flo's - to make it basically a no-op for things on which `CGI.escapeHTML` doesn't operate.

**Comment by dylanahsmith** [comment]
It looks like it has been there since the "Initial github import of liquid" commit 1d647361e1a39ee09f1bd2d62701925c0128c578, and no one has been brave enough to remove it.  However, it could easily hide a vulnerability, possibly from encoding causing the escaping to raise an encoding error.

We should check how often that rescue path is in Shopify by adding a StatsD increment for the rescue path, then remove it with more confidence.  We could do that by removing it in liquid, then monkey patching it with a rescue that does the StatsD increment and returns the input, to keep the StatsD logic out of liquid.

**Comment by nybblr** [comment]
@dylanahsmith next step then? Just submit a PR that strips out the offending rescue?

**Comment by fw42** [comment]
Yeah :+1: to removing the rescue here (and probably flagging the PR as not backwards compatible).

**Comment by pushrax** [comment]
I tried exploiting this in Shopify a couple months ago but was unable to. It's possible to make it return unescaped input in certain circumstances if you can pass certain characters in certain encodings.

The rescue should definitely be removed.
