### ISSUE TITLE
Get Current URL

### ISSUE THREAD

**Issue by gina3five** [Shopify/liquid#525]
I have yet to see a way to get the current page URL as seen in the address bar with liquid. Did I miss something?
Would it be complicated to add another global variable, similar to {{ page_title }}, to get the current page URL, including any query strings?
Thanks!

**Comment by fw42** [comment]
Liquid does not know anything about URLs or address bars or websites and such...

Are you using Jekyll?

**Comment by gina3five** [comment]
I guess that's why I haven't seen a solution for that yet!

I'm just working within Shopify.

**Comment by rickydazla** [comment]
@gina3five @fw42 Shopify _does_ *know* about some URLs that you might get some mileage from, depending what template you are on and what you are trying to do. All of the following will return URL-related value strings... 
* shop.url
* shop.domain
* page.url
* collection.url
* product.url
* blog.url
* article.url
* article.comment_post_url

**Comment by gina3five** [comment]
Yep, I'm aware of those. There are a couple things I would like to check with liquid I can't get with those. For example, the URL of a hidden product. If someone tries to go to a product URL of a product that is hidden, you are shown the 404 page. Since you're on the 404 template, you don't have access to the product object. 

Also, it would be neat to get the current URL as seen in the address bar so I can get any query string, such as the search type when on the search results page (/search?type=product&q=plates) or any other information I want to pass.

My knowledge of how liquid works is really limited, so sorry for asking a dumb question.

**Comment by Kottmaskinen** [comment]
@gina3five I was trying to find this as well. The solution I had to turn to was using JS document.url instead. Not a very nice one, but it's the best I could do.

**Comment by DrTwister** [comment]
I am also looking for this information. Unfortunately the way shopify is structured, per comment above, you can only find a page.url or blog.url etc. The problem with this is that you need some type of case statement to determine which page a user is on. To make matters more complicated, if a user creates custom pages, then you need to inlcude additional use cases based on those additional variations.

As far as I can tell, there is no singular request to get the current page url, title, handle, etc, despite what template or element is selected.

**Comment by srinathperera101** [comment]
Hi I was able to get this by 
{% assign current_url = '' %}

{% case template %}
	{% when 'page' %}
		{% assign current_url = page.url %}
	{% when 'blog' %}
		{% assign current_url = blog.url %}
	{% when 'article' %}
		{% assign current_url = blog.url %}
	{% when 'collection' %}
		{% assign current_url = collection.url %}
	{% when 'product' %}
		{% assign current_url = product.url %}
{% endcase %}

**Comment by joe-dempsey** [comment]
There are times when you need to get more than the above liquid code will give as there are additional url parameters added at certain stages (e.g. purchasing then forced to log in, submitting email etc) - then you need to use javascript:

`$(document).ready(function() {
	//jquery
    $(location).attr('href');

	//pure javascript
	var pathname = window.location.pathname;
	
});`

**Comment by AJDinmore** [comment]
In case it's of use to anyone:

What Shopify does have, which may or may not help you, is the canonical_url variable/object. It doesn't technically give the current URL and definitely won't include any query parameters, but in a lot of cases it's probably going to have the needed information.

https://help.shopify.com/themes/liquid/objects#canonical_url

**Comment by 1der1** [comment]
Shopify ignores the querystring part of requests. If you look at the source code of a Shopify page, you can even see that you get cached results for requests with another querystring.

Example:
You call https://myshop.com?123
The source code contains
"pageurl":"myshop.com?123"

Then you call https://myshop.com?1234
The source code may again contain
"pageurl":"myshop.com?123"

This behavior is server side and there is no way you can change this. If have seen feature requests for accessing the querystring for years.

I have given up hope, that this feature will ever come to Shopify.

I have learned, that in order to get the querystring into liquid code you have to use a proxy app.

A proxy app is installed on a non-Shopify server and is called with the full URI of the requested page. The proxy app can add Liquid code to be used in the Shopify server. This way the proxy app can inject the querystring information.

I have asked for a solution in the Shopify forum:
https://ecommerce.shopify.com/c/shopify-discussion/t/querystring-part-of-a-url-427478

I did not get feedback so far. However, I now found an old app
https://apps.shopify.com/querystring

This should help solve the problem as soon as it is updated to the current Shopify theme structure. I am currently in discussion with the App developer.

**Comment by 1der1** [comment]
Unfortunately, this is the answer I got from Joe Bryan at www.sinelabs.com:
_> ...there is only one path that this app works with and you can only configure it in the app proxy url screen. They have no /pages/ path because that is used for built-in pages. This app will not work for what you want. Please uninstall. Snippets and paths work the way they do in normal Shopify yes, but in a proxy app (and anyone can build one) it is different what can be rendered and at what path. The path you want to use will not work, never will work. It is not a limitation of our app but of what a proxy app can do by Shopify._

I have now made a feature request for Shopify:
Dear Shopify team,

What about an include directive for external HTML/Liquid code?
{% external <url> %}
<url> being on an external server page, which receives the Shopify page address (including the query string) and gives back Content-Type: application/liquid.

This way you could specify the position of the content within the Shopify page like you can do with the {% include %} directive. The content would just come dynamically from an external server instead of including a Shopify theme snippet.

This solution would be very powerful without compromising the Shopify architecture.

**Comment by laneystroup** [comment]
Did you guys try request.path? I did not test to see if it includes the query string, but it works great for getting the current url. See https://help.shopify.com/themes/liquid/objects/request.

**Comment by 1der1** [comment]
Yes, I tried everything. The query string is not existent for the Shopify server and cannot be used in Liquid.

Using non-documented page data sent by the server, you can hack the query string. Unfortunately, the Shopify server cache ignores the query string as well, and you can get the same page from the server, no matter what query string. E.g., even the hacked data in the page code are wrong and useless then.

Ignoring the query string entirely is the biggest Shopify weakness in my opinion.

I can understand the reasons and they are valid most of the time, but there should be a way to override it when it is required. For this reason, I have suggested the {% external %} solution which would not break anything else but support third-party developers a lot.

**Comment by qrcf** [comment]
Any updates on this issue?

**Comment by qrcf** [comment]
Want to use more advanced sorting such as size and need it to be in the query string but there appears to be no way to reliably get this. I don't want to be forced to make the collection page sort via javascript.

**Comment by 1der1** [comment]
I have seen requests for this feature for years, and I assume they will not change the behavior because it affects Shopify's server-side caching. Only a few special handles support query parameters.

It's a pity because Liquid and Metafields would be much more powerful with query parameters.

Javascript is the only way for now.

**Comment by jeffreyhshapiro** [comment]
Commenting just in case there are updates on the issue.  Parsing URL params in Liquid would be really advantageous.

**Comment by msvitek** [comment]
I'd love an option to access query string params as well. I need a way to add different open graph tags based on the query string param.

**Comment by lindseybradford** [comment]
Years of developer requesting the ability to request params and no movement. This is utterly ridiculous.

**Comment by MS-Jahan** [comment]
> Years of developer requesting the ability to request params and no movement. This is utterly ridiculous.

YEAP!!!!

**Comment by rickydazla** [comment]
Dudes. There are apps... and javascript.

**Comment by Christopher-Hayes** [comment]
The whole point of Liquid is to do the work server-side, Javascript is doing work that could've been done server-side. It would be nice if this feature was added.

**Comment by ADTC** [comment]
> Hi I was able to get this by
> ```
> {% assign current_url = '' %}
> 
> {% case template %}
> {% when 'page' %}
> ...
> ```

In Shopify, `request.path` works universally so you don't need this. Or if you're specifically looking for a `.url`, you can add `request.path` as a final fallback:
```
{% else %}
{% assign current_url = request.path %}
```

**Comment by rickydazla** [comment]
@joshpugh you can use something like `{{- 'Disallow: /*?q=*' }}` in robots.txt.liquid — ref https://help.shopify.com/en/manual/promoting-marketing/seo/editing-robots-txt

**Comment by joshpugh** [comment]
Sorry yeah I have the robots.txt in place, but was hoping to double down!

**Comment by galbaras** [comment]
> @srinathperera101 In Shopify, `request.path` works universally so you don't need this.

Alas, it doesn't. When handling 404 errors, the `request` object refers to the 404 page, NOT the page that's not found, and I see no way of getting that value, because it's not in the HEAD content either 😞

**Comment by galbaras** [comment]
Also, since `template` can be equal to `404`, why is there no matching object with properties like `page` and `product`? I guess it can't be called `404`, but I can't find any matching template objects in the documentation.

**Comment by znemeth23** [comment]
I just stumbled upon this issue, it's so strange that such a simple thing cannot be done in Liquid and you have to resort to those `content_for_header` hacks (splitting a 100+ line JS code to obtain the `pageurl` from there)...
