### ISSUE TITLE
Error Modes make no difference

### ISSUE THREAD

**Issue by youroff** [Shopify/liquid#533]
I'm trying to play with various error modes:

```
2.1.2 :005 > t = Liquid::Template.parse("{{some ", error_mode: :warn)
Liquid::SyntaxError: Liquid syntax error: Variable '{{' was not properly terminated with regexp: /\}\}/
```

So use of :warn makes no difference, it still raises an exception. Maybe I misunderstand something?
Version of liquid is 3.0.1

**Comment by AlanMcCann** [comment]
Seems to be an issue back to 3.0.0

**Comment by pushrax** [comment]
`error_mode` is actually only applicable to syntax errors inside tags. For instance:

```
> Liquid::Template.parse("{{some foo}}", error_mode: :warn)
works
> Liquid::Template.parse("{{some foo}}", error_mode: :strict)
syntax error
```

The original regex-based parser allows almost any syntax, however one of the few errors is having malformed tag delimiters like in the example given in the OP. The way `error_mode: :warn` works is by running the new parser, and if there are any errors thrown running the old parser. Since the given template causes an error in the old parser as well, an error propagates out of the original call.

The correct way to handle this is by rescuing outside of the parse call as in the post above, sorry about the naming confusion.

**Comment by AlanMcCann** [comment]
Thanks for the quick response. I understand the thinking now.
