### ISSUE TITLE
Liquid performance is slow

### ISSUE THREAD

**Issue by maya** [Shopify/liquid#598]
I hear a lot that Ruby's implementation of Liquid is slow. Is this something that is being worked on? This affects a lot of people that use Liquid on Jekyll websites.

**Comment by fw42** [comment]
Yes, it's in our best interest to make Liquid (and Jekyll) as fast as possible. Having an open issue like this is however not very helpful (super generic, there is no definition of "slow", no way to know when this issue is "solved", no way to reproduce a specific problem, ...).

**Comment by maya** [comment]
@fw42 Glad to hear you are working on this and sorry for the lack of specificity. Where can I see where this work is being done around this? Is there a better issue, branch, PR etc you could point me to?

**Comment by parkr** [comment]
There are a bunch of performance PR's on the Jekyll repo, some of which Florian here wrote! We definitely need to work on it and we have focused on it in Jekyll 3 development.

**Comment by fw42** [comment]
I did some Liquid-related Jekyll optimizations in https://github.com/jekyll/jekyll/pull/3762 and https://github.com/jekyll/jekyll/pull/3693. Also related: https://github.com/jekyll/jekyll/pull/3762.

We are not doing a good job with adding labels to pull requests, so it's hard to say which old PRs were performance related, but if you look at recently merged PRs by pushrax or dylanahsmith, many of those were performance-related.

As for Jekyll specifically: Version 3 ships incremental regeneration, which in my opinion is the best thing since sliced bread. You should check it out.

**Comment by fw42** [comment]
@maya: If you have a public Jekyll site with source code that I could look at that you think is particularly slow, I would be happy to check it out and see if there are any obvious Liquid bottlenecks.
