### ISSUE TITLE
Not properly terminated errors being reported as not closed errors

### ISSUE THREAD

**Issue by benbalter** [Shopify/liquid#663]
Running integration tests to update GitHub Pages to Liquid 3, it seems there may be a regression around error reporting.
### Liquid 3.0.6

```
irb(main):003:0> Liquid::Template.parse("{% capture foo }\nbar\n{% endcapture %}").render!
Liquid::SyntaxError: Liquid syntax error: 'capture' tag was never closed
```
### Liquid 2.6.2

```
irb(main):004:0> Liquid::Template.parse("{% capture foo }\nbar\n{% endcapture %}").render!
Liquid::SyntaxError: Tag '{%' was not properly terminated with regexp: /\%\}/
```

I'd expect the error message from the first case if it were:

```
{% capture foo %}
bar
```

But in this case, the capture tag is "closed", I'd expect the "not properly terminated with regexp" error, which is more accurate, and helps point the user at what actually's the problem.

/cc @parkr as it may be related to https://github.com/Shopify/liquid/issues/656

**Comment by fw42** [comment]
@trishume @pushrax, mind taking a look?

**Comment by trishume** [comment]
I don't remember all of my Liquid context but I think what is happening here is that the tag tokenization code changed. Because Liquid accepts all sorts of weird stuff in tags, the 3.0.6 example above is treating  ` capture foo }\nbar\n{% endcapture ` as the contents of the tag, which looks like a capture with some argument stuff, and then the string ends without a closing tag for that `capture`.

I think the change that introduced this was that PR which enabled quoting the `}` in a string. That changed the tag ending search logic to not indiscriminately stop on `}` characters, which causes the regex search to find the closing `%}` of the end tag and treat it as one tag.

I'm not sure there is a clean fix for this.

**Comment by parkr** [comment]
Hey, is this still something you'd like to look further into? We have been running Liquid 3 for a while and things seem fine so far.

**Comment by pushrax** [comment]
A clean fix for this doesn't exist, as Tristan described.
