### ISSUE TITLE
Liquid - Tags inside Block

### ISSUE THREAD

**Issue by rjurado01** [Shopify/liquid#669]
I am new with Liquid Templating language. I have this custom Block tag and code:

```ruby
    class CustomBlock < Liquid::Block
      def initialize(tag_name, params, tokens)
        @names = ["Name1", "Name2"]
      end
    
      def render(context)
        Liquid::Template.parse(super).render('names' => @names)
      end
    end
    
    Liquid::Template.register_tag('custom', CustomBlock)
    template = "{% custom %}{% for name in mames %}Hello {{name}}.{% endfor %}{% endcustom %}"
    Liquid::Template.parse(template).render
```

It don't let me use tags inside block, when I print super in render function it is equal to: 'Hello .'
'{% for ... %}' tag and '{{name}}' has been removed.

Any help? Thanks.

**Comment by pushrax** [comment]
First, you have a typo. `for name in mames`

Second, unless you're actually trying to generate and re-parse Liquid code within your custom tag, instead of calling `parse` you should set `context['names'] = @names` and then call `super`. In the current code, the call to `super` will actually render the block contents, and pass that rendered output for further rendering. Here's something to try:

```ruby
def render(context)
  context['names'] = @names
  super
end
```

If you'd like to avoid overwriting an existing "names" key in your context, take a look at the `context.stack` function.

**Comment by fw42** [comment]
Closing this. Please reply if you want this re-opened.

**Comment by rjurado01** [comment]
@pushrax Thanks!!
