### ISSUE TITLE
Allow more flexible variable passing for include

### ISSUE THREAD

**Issue by brendon** [Shopify/liquid#740]
Currently it is my understanding that `include` only allows one object to be passed in.

Jekyll has a nice implementation of `include` that allows for more than one variable to be passed to the include. Their tag is fairly specific to the Jekyll implementation, but I wondered if you'd be open to extending the current implementation of include to allow for named variables?

https://jekyllrb.com/docs/templates/#includes

**Comment by NathanPJF** [comment]
@brendon I pass multiple variables with `include` often.  In the docs on it gives an example: https://docs.shopify.com/themes/liquid/tags/theme-tags#include

```
{% include 'snippet', snippet_variable: 'this is it', snippet_variable_two: 'this is also it' %}
```

I made a gist awhile ago showing someone how to past multiple variables: https://gist.github.com/NathanPJF/4ba354ba65071532edb4

Hopefully that helps, but I'm curious if this isn't what you're looking for.  I read the page you linked.  Instead of `{{ include.param }}`, you can just say `{{ param }}` inside the snippet.

**Comment by brendon** [comment]
Ah I see, that's interesting. Is that just a quirk of the syntax for tags or a part of liquid itself? I was just going off the documentation in the source code itself:

https://github.com/Shopify/liquid/blob/master/lib/liquid/tags/include.rb

And despite my searching, never managed to come across that documentation :D Thanks for providing it. I'll give it a go.

My only concern is leakage of the variables outside the include. Are these inline variables still available in the parent template if defined within the include statement? :)

Thanks again for your help!

**Comment by ConduciveMammal** [comment]
Sorry to jump on this super old top, but I've just noticed this doesn't seem to work for sections, when using `{% section 'collection-template', prod_per_page: 12 %}`, I get an error returned saying:

> Error in tag 'section' - Valid syntax: section '[type]'

Can this be adapted for this scenario please?
