### ISSUE TITLE
Liquid::UndefinedVariable is raised for defined attribute with nil value, when strict_variables: true

### ISSUE THREAD

**Issue by nijikon** [Shopify/liquid#749]
``` ruby
2.3.0 :001 > Liquid::Template.parse("{{foo}}").render!({ 'foo' => nil}, strict_variables: true)
Liquid::UndefinedVariable: Liquid error: undefined variable foo
```

Is this desired behaviour?

We want to be strict for variables being defined, nil value is allowed because we handle that with an if.

**Comment by dylanahsmith** [comment]
That seems like a bug to me.

**Comment by pascalbetz** [comment]
We currently have the same problem. Variable is defined but `nil` and this causes mentioned error.
I think the problem lies with `Liquid::Context#find_variable` (https://github.com/Shopify/liquid/blob/master/lib/liquid/context.rb#L163). 


The check for `unless value` (https://github.com/Shopify/liquid/blob/master/lib/liquid/context.rb#L174) does not take `nil` into account which is a valid value when `raise_on_not_found` is set. 

If there is any chance that this gets accepted i'll craft a PR. Let me know.

**Comment by fw42** [comment]
Happy to look at a PR
