### ISSUE TITLE
[question] Caching parsed templates?

### ISSUE THREAD

**Issue by jeroenvisser101** [Shopify/liquid#760]
Hi guys, I really like liquid, but I'm wondering how you do the expensive parsing/compiling so that it can be cached (to disk/memcached/redis).

> It has to be stateless. Compile and render steps have to be separate so that the expensive parsing and compiling can be done once and later on you can just render it passing in a hash with local variables and objects.

The docs/wiki don't mention how to accomplish this (except that you can parse once and render many times in 1 request).

**Comment by fw42** [comment]
At Shopify, we don't cache parsed templates (as far as I know), only the rendered output. Rendering is much more expensive for us (since it reads data from the database). If I remember correctly, we did some benchmarks a while ago and parsing templates (without rendering them) was on average less expensive than a roundtrip to our cache servers, so we decided it wasn't really worth it.

That being said, I also did some experimentation with Liquid in Jekyll and tried caching parsed templates in memory, and there I actually saw a measurable performance increase (our biggest Jekyll site builds in about 45 seconds on my laptop and caching the parsed templates shaves off about 3-4 seconds of that).

For caching the rendered output (i.e. the HTML), we use a custom pagecache that we wrote (https://github.com/Shopify/cacheable). But you can use pretty much whatever you like here.

Hope that helps.

**Comment by jeroenvisser101** [comment]
@fw42 thanks, that helps for sure. Can you share anything on how you decide wether to cache the output or not? (I guess in the case of Shopify, you don't cache people with carts, to prevent weird things?)

**Comment by jeroenvisser101** [comment]
I might have found some more info [here](https://github.com/Shopify/cacheable/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R21), thanks!

**Comment by fw42** [comment]
Cool. Gonna close this then.

**Comment by dylanahsmith** [comment]
> If I remember correctly, we did some benchmarks a while ago and parsing templates (without rendering them) was on average less expensive than a roundtrip to our cache servers, so we decided it wasn't really worth it.

That isn't true.  We prototyped caching the parsing during hack days and it is totally worth it.  It doesn't add an extra round trip because we don't need to the round trip to get the template if we get the parsed template from the cache.

We just haven't prioritized shipping that work.

**Comment by pushrax** [comment]
That was also before Liquid-C.

**Comment by jeroenvisser101** [comment]
@dylanahsmith 
> We prototyped caching the parsing during hack days and it is totally worth it. It doesn't add an extra round trip because we don't need to the round trip to get the template if we get the parsed template from the cache.

Is that something that you're able to share?

@pushrax 
> That was also before Liquid-C.

I guess that might make the speed improvement negligible.

**Comment by dylanahsmith** [comment]
In that prototype we just used `Marshal.dump` to cache the result of `Liquid::Template.parse(template_source)`.  We also tried to cache partials where possible using the changes in https://github.com/Shopify/liquid/compare/include_parsing_at_parse_time

**Comment by jeroenvisser101** [comment]
@dylanahsmith thanks, that helps!

**Comment by derekharmel** [comment]
@dylanahsmith Looking at the implementation of `Liquid::Template#render` [here](https://github.com/Shopify/liquid/blob/master/lib/liquid/template.rb#L162), I'm wondering if it's possible to re-use an instance of `Liquid::Template.parse` without the `Marshal` trick by simply constructing my own instance of `Liquid::Context` and passing it to `#render`. It looks like most of the state mutation happens to the context with the only modification to the template being to `@assigns`, `@instance_assigns`, and `@registers` but happening via their inclusion in `Context.new`. 

To rephrase, if I create my own `Liquid::Context` for `#render`, can I avoid mutation of the template instance and allow for the possibility of re-using the template without have to re-parse for every render?
