### ISSUE TITLE
undefined method 'to_liquid' for Rails Associations

### ISSUE THREAD

**Issue by kieraneglin** [Shopify/liquid#762]
#### Versions
- Rails 5 beta 3
- Liquid 3.0.6
- I am not using Redcloth

#### Steps to reproduce
Given a model `User` that `has_many :publications`, I want to iterate over each `publication` to show it's title, date created, etc,.

**user.rb:**
```Ruby
class User < ApplicationRecord
  has_many :publications
  ...
  def to_liquid
    {
      ...
      publications: publications.all
      ...
    }.stringify_keys
  end
end
```

**publication.rb:**
```Ruby
class Publication < ApplicationRecord
  belongs_to :user
  ...
  def to_liquid
    {
      ...
      title: title
      ...
    }.stringify_keys
  end
end
```

**liquid template:**
```Html
{% for publication in user.publications %}
  {{ publication.title }}
{% endfor %}
```
___
#### Expected output
A list of the titles of all publications a user owns

#### Actual output
```
Liquid error: undefined method `to_liquid' for #<Publication::ActiveRecord_Associations_CollectionProxy:0x007ffd9f2a9b90> 
```
#### Extra
I consulted the docs, but I couldn't find anything related to what I'm trying to do.  

Adding an empty method called `self.to_liquid` stopped the error, but there was no output.

**Comment by dylanahsmith** [comment]
Convert your active record scope to an array so that it can be iterated over with liquid.  E.g. you can use `publications.to_a` instead of `publications.all`

Liquid intentionally doesn't let liquid control arbitrary objects.  For instance, you wouldn't want untrusted users to be able to manipulate what SQL query is performed, without having explicit control over what they can do with it by wrapping it in a liquid drop.

**Comment by prdetective** [comment]
So I stumped upon this issue when updating some old code to Rails 5. Used this to solve:

```ruby
# config/initializers/liquid.rb
module ActiveRecord
  class Relation
    def method_missing(name, *args, &block)
      return super unless name == :to_liquid

      to_a.to_liquid
    end

    def respond_to_missing?(name, include_private = false)
      name == :to_liquid || super
    end
  end
end
```

**Comment by brendon** [comment]
Perhaps if `liquid` found `Enumerable` in the objects ancestors it could iterate over the object and call `to_liquid` on each item? Perhaps it was already doing this? Would this have been a security issue?

**Comment by dylanahsmith** [comment]
The problem happens when evaluating the expression `user.publications`, not specifically in the `for` tag, so the security concern would come from trying to access arbitrary other methods on the relation (e.g. `user.publications[arbitrary_property]`).

**Comment by brendon** [comment]
Ok makes sense. I think somewhere along the line `liquid` stopped iterating iterable objects and now explicitly checks for an array.

I already had all my models with a `to_liquid` method and `liquid` used to cast each of the items in an AR relation `to_liquid`. In my Drops I was just delegating relation methods to the underlying object (which used to work) but now I have to create a custom method in the Drop and call `the.relation.to_a` instead. No biggie but it was confusing due to `Liquid::InternalError` vagueness. :D
