### ISSUE TITLE
Shopify translation ('t') filter

### ISSUE THREAD

**Issue by japherwocky** [Shopify/liquid#791]
Sorry that this is more of a question / clarification than a bug!

Shopify's version of liquid has a translate filter (`t`): https://help.shopify.com/themes/development/internationalizing/translation-filter

I don't see that filter in this codebase or in the github.io documentation.  This is something custom they've added?  

Is that intentional?  Are there any plans to bring that filter into this repository?

The context being, I would very much like to add a very small feature to it, but I am not sure it's an option.  And again, this is probably better answered by the Shopify staff, but it's proving a bit too technical for the support channels.

Thank you for any insight!

**Comment by fw42** [comment]
yea you are right, the translate (t) filter is not part of Liquid itself, but only available in Shopify.

What is it that you would like to change/fix?

**Comment by japherwocky** [comment]
It would be really convenient if the filter could take an optional language param to override (I assume?) the Accept-Language header coming from the browser. 

The use case being, we'd like to respect the browser on the main site, but also serve language specific subdomains, eg fr.ourshop.com, that always/only serves the shop in French.

**Comment by fw42** [comment]
ping @davidcornu since he implemented that filter in Shopify

**Comment by davidcornu** [comment]
Hey @japherwocky!

> I don't see that filter in this codebase or in the github.io documentation. This is something custom they've added?

The `t` filter is custom. It's basically a wrapper around the [i18n gem](https://github.com/svenfuchs/i18n) with a backend that reads from the theme's `locales` directory.

> Is that intentional? Are there any plans to bring that filter into this repository?

That is intentional. In their current form, the filters we added to support translated themes ([`| t`](https://help.shopify.com/themes/development/internationalizing/translation-filter), `| sentence`,  modifications to [`| date`](https://help.shopify.com/themes/development/internationalizing/locale-files#date-localization)) are very Shopify-specific and would be of little use to other Liquid users. 

> It would be really convenient if the filter could take an optional language param to override (I assume?) the Accept-Language header coming from the browser.
>
> The use case being, we'd like to respect the browser on the main site, but also serve language specific subdomains, eg fr.ourshop.com, that always/only serves the shop in French.

- We determine the language based on the Shop's setting (found under <kbd>Online Store</kbd> &rarr; <kbd>Themes</kbd> &rarr; <kbd>•••</kbd> &rarr; <kbd>Edit language</kbd>)
- The goal of our internationalization support is to allow users to easily change the language of their theme (by either selecting from the available translations or by creating their own)
- We have no immediate plans to allow multiple languages to be active at the same time (you can however achieve this with https://apps.shopify.com/langify).

Hope that helps.

**Comment by japherwocky** [comment]
Oh I see, I guess I misunderstood how it was used.  Yep, my client is using langify, it's OK but a bit of a pain point.

Thank you both!
