### ISSUE TITLE
Convert an integer to a number in text

### ISSUE THREAD

**Issue by thomasvbeek** [Shopify/liquid#823]
I was looking around but couldn't find the option to format an integer into a text string, e.g.: 1 = one, 2 = two.

So if I would be doing something like this:
{% assign value = 20 %}{{ value | format_to_string }}

It would return: twenty. Is there any way this is already possible or can we make this possible?

**Comment by pushrax** [comment]
If you're running your own Liquid, you could create this filter in your codebase. Otherwise (GH Pages/Jekyll, Shopify, etc), the easiest way is a lookup table, something like

```
{% case value %}{% when 0 %}zero{% when 1 %}one ....
```

If you need support for arbitrarily big numbers then you'll need something algorithmic. I don't think we'll ever add that to Liquid itself.
