### ISSUE TITLE
Undocumented Things

### ISSUE THREAD

**Issue by odigity** [Shopify/liquid#852]
Hello, Shopify.  I just discovered Liquid a few days ago (as a result of discovering Jekyll (as a result of discovering GitHub Pages)), and decided to take the time to read all the docs from end-to-end while taking notes.  I discovered some things that were not included in the primary user documentation (http://shopify.github.io/liquid/).

### Comments

    Any content that you put between {% comment %} and {% endcomment %} tags is turned into a comment.

Source: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#comments

### Raw

    Raw temporarily disables tag processing. This is useful for generating content (eg, Mustache, Handlebars) which uses conflicting syntax.

    {% raw %}
      In Handlebars, {{ this }} will be HTML-escaped, but {{{ that }}} will not.
    {% endraw %}

Source: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#raw

### Helper Variables

    During every for loop, the following helper variables are available for extra styling needs:

    forloop.length      # => length of the entire for loop
    forloop.index       # => index of the current iteration
    forloop.index0      # => index of the current iteration (zero based)
    forloop.rindex      # => how many items are still left?
    forloop.rindex0     # => how many items are still left? (zero based)
    forloop.first       # => is this the first iteration?
    forloop.last        # => is this the last iteration?

Source: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#helper-variables

### Chaining Filters

    Multiple filters can be used on one output. They are applied from left to right.

Source: https://help.shopify.com/themes/liquid/filters

### forloop.parentloop

    Add forloop.parentloop as a reference to the parent loop (#520) [Justin Li]

Source: https://github.com/Shopify/liquid/blob/master/History.md

**Comment by admhlt** [comment]
@odigity, this is awesome!

I'm most often the one who makes documentation updates, and this stuff is definitely missing! You're more than welcome to make a PR to our `gh-pages` branch if you'd like to test your Jekyll skills.

I'll assign this issue to myself so that if you don't want to take it on I'll get to it eventually.

**Comment by gina3five** [comment]
Any chance Shopify can put together some sort of notification system when something changes in the docs/code base? I'm trying to figure out the best way to stay on top of new stuff with regards to Shopify development. I always hate stumbling upon something new (to me) and finding out that it was released weeks or months ago.

**Comment by yaobinwen** [comment]
Hi, @admhlt , I found these tags are already documented in the [Shopify Help Center documentation](https://help.shopify.com/themes/liquid/tags/theme-tags#raw). I'm actually curious why the help center documentation is more recent than the [Liquid official documentation page](https://shopify.github.io/liquid/) because, from the software engineering perspective, this misalignment might reveal some problem in the development process.

**Comment by admhlt** [comment]
You're right @yaobinwen. In some cases, Shopify Liquid docs and official Liquid docs differ because they are [different variations of Liquid](http://shopify.github.io/liquid/basics/variations/), but in this case it's just a case of someone forgetting to add that stuff to the official Liquid docs.

I would love for all Liquid documentation to be single-sourced, and hopefully someday it will all be the same and consistent. But so far I haven't had the bandwidth to dedicate a lot of time to that. If you have any ideas, I'd be happy to chat about them.
