### ISSUE TITLE
sorting with two or more properties

### ISSUE THREAD

**Issue by lw5946** [Shopify/liquid#986]
How could I sorting by two or more page's properties?
I want to sort my blog by date and user-defined attribute.

**Comment by ngeor** [comment]
I was wondering if we could reopen this issue. It seems this isn't supported, but it's not clear why the issue was closed.

I use the "sort" filter to sort a collection of pages in a Jekyll blog (which uses liquid). Each page has two properties, "post_count" and "title".

Currently I use this:

```
{% assign tags = site.tag | sort: "post_count" | reverse %}
```

but pages that have the same `post_count` end up in random order. I would like to sort first by `post_count` in descending order and then by `title` in ascending order.

So something like:

```
{% assign tags = site.tag | sort: "post_count DESC, title ASC" %}
```
